---
kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
    - npm install
    - npm run generate -- -d public

- name: publish
  image: plugins/gh-pages
  settings:
    username:
      from_secret: git_deploy_key
    password: x-oauth-basic
    pages_directory: public/

- name: notify
  image: drillster/drone-email
  settings:
    from: ci@lecat.io
    host: mail.lecat.io
    secrets: [ email_username, email_password ]
  when:
    status:
    - failure

trigger:
  branch:
  - master
  event:
  - push
