---
kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
    - npm install
    - npm run generate -- -d public
    - cp ./CNAME ./public/CNAME

- name: publish
  image: plugins/gh-pages
  settings:
    ssh_key:
      from_secret: deploy_key
    pages_directory: public/
    exclude_cname: false

- name: notify
  image: drillster/drone-email
  settings:
    from: ci@lecat.io
    host: mail.lecat.io
    secrets: [ email_username, email_password ]
  when:
    status:
    - failure

trigger:
  branch:
  - master
  event:
  - push
