stages:
  - build
  - publish
before_script:
  - mkdir -p ~/.ssh
  - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan git.lecat.pro > ~/.ssh/known_hosts

build:
  image: node
  stage: build
  artifacts:
    paths:
      - public/
  script:
    - npm install
    - npm run generate -- -d public
    - cp ./CNAME ./public/CNAME

publish:
  image: node
  stage: publish
  script:
    - npm install -g --silent gh-pages
    - git config user.email "git@lecat.io"
    - git config user.name "GitLab CI"
    - git remote rm origin && git remote add origin "git@git.lecat.pro:${CI_PROJECT_PATH}.git"
    - gh-pages --dist public
